language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=trojsten.settings.production TROJSTENWEB_FACEBOOK_KEY='' TROJSTENWEB_FACEBOOK_SECRET='' TROJSTENWEB_GOOGLE_OAUTH2_KEY='' TROJSTENWEB_GOOGLE_OAUTH2_SECRET='' TROJSTENWEB_GITHUB_KEY='' TROJSTENWEB_GITHUB_SECRET='' TROJSTENWEB_DATABASE_USER=postgres TROJSTENWEB_KASPAR_DATABASE_USER=postgres

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ./manage.py test
sudo: false
addons:
    code_climate:
        repo_token: a2d4a42a85b041da0c9d964e43de5a0bd632e7191ce66b262f6fdbe4fef83047
