language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q "Django${DJANGO_VERSION}"
  - pip install -q coverage
# command to run tests
script:
  - coverage run --source='.' manage.py test
sudo: false
addons:
    code_climate:
        repo_token: a2d4a42a85b041da0c9d964e43de5a0bd632e7191ce66b262f6fdbe4fef83047
