version: "3.7"

x-web: &web
  image: trojsten/web:latest
  build:
    context: .
    dockerfile: ./docker/prod/Dockerfile
  volumes:
    - .:/web

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      trojsten:
        ipv4_address: 10.47.0.2
    environment:
      - POSTGRES_USER=trojsten
      - POSTGRES_DB=trojsten
  ksp:
    <<: *web
    ports:
      - "8001:80"
    env_file:
      - ./docker/prod/web.env
    environment:
      - DJANGO_SETTINGS_MODULE=trojsten.settings.ksp
      - TROJSTENWEB_ALLOWED_HOSTS=ksp.sk;beta.ksp.sk;localhost;127.0.0.1;
      - TROJSTENWEB_LOGIN_KEY
      - TROJSTENWEB_LOGIN_SECRET
    networks:
      trojsten:
        ipv4_address: 10.47.0.101
    depends_on:
      - db
      - login
  prask:
    <<: *web
    ports:
      - "8002:80"
    env_file:
      - ./docker/prod/web.env
    environment:
      - DJANGO_SETTINGS_MODULE=trojsten.settings.prask
      - TROJSTENWEB_ALLOWED_HOSTS=prask.ksp.sk;beta.prask.ksp.sk;localhost;127.0.0.1;
      - TROJSTENWEB_LOGIN_KEY
      - TROJSTENWEB_LOGIN_SECRET
    networks:
      trojsten:
        ipv4_address: 10.47.0.102
    depends_on:
      - db
      - login
  fks:
    <<: *web
    ports:
      - "8003:80"
    env_file:
      - ./docker/prod/web.env
    environment:
      - DJANGO_SETTINGS_MODULE=trojsten.settings.fks
      - TROJSTENWEB_ALLOWED_HOSTS=fks.sk;beta.fks.sk;localhost;127.0.0.1;
      - TROJSTENWEB_LOGIN_KEY
      - TROJSTENWEB_LOGIN_SECRET
    networks:
      trojsten:
        ipv4_address: 10.47.0.103
    depends_on:
      - db
      - login
  login:
    <<: *web
    ports:
      - "8010:80"
    networks:
      trojsten:
        ipv4_address: 10.47.0.110
    depends_on:
      - db
    env_file:
      - ./docker/prod/web.env
    environment:
      - DJANGO_SETTINGS_MODULE=trojsten.settings.login
      - TROJSTENWEB_LOGIN_KEY
      - TROJSTENWEB_LOGIN_SECRET
      - TROJSTENWEB_ALLOWED_HOSTS=localhost;127.0.0.1;10.47.0.110
      - TROJSTENWEB_FACEBOOK_KEY
      - TROJSTENWEB_FACEBOOK_SECRET
      - TROJSTENWEB_GOOGLE_OAUTH2_KEY
      - TROJSTENWEB_GOOGLE_OAUTH2_SECRET
      - TROJSTENWEB_GITHUB_KEY
      - TROJSTENWEB_GITHUB_SECRET

volumes:
  db_data:

networks:
  trojsten:
    ipam:
      config:
        - subnet: 10.47.0.0/16
